const PDFDocument = require("pdfkit");

function generatePDF(res, result) {
  const doc = new PDFDocument({ margin: 40 });

  // ================= HEADERS =================
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=resume-report.pdf",
  );

  doc.pipe(res);

  // ================= TITLE =================
  doc
    .fillColor("#38bdf8")
    .fontSize(22)
    .text("Resume Analysis Report", { align: "center" });

  doc.moveDown(0.5);

  doc
    .fillColor("#94a3b8")
    .fontSize(10)
    .text("AI-powered ATS Evaluation", { align: "center" });

  doc.moveDown(2);

  // ================= SCORE BOX =================
  const boxY = doc.y;

  doc.roundedRect(40, boxY, 520, 70, 10).fillAndStroke("#0f172a", "#38bdf8");

  doc
    .fillColor("white")
    .fontSize(18)
    .text(`Match Score: ${result.score || 0}%`, 60, boxY + 15);

  doc
    .fontSize(12)
    .fillColor("#94a3b8")
    .text(
      `Keyword: ${result.keywordMatchPercentage || 0}%   |   Experience: ${result.experienceMatchPercentage || 0}%`,
      60,
      boxY + 40,
    );

  doc.moveDown(4);

  // ================= SECTION FUNCTION =================
  const section = (title, items, color = "#38bdf8") => {
    doc.moveDown(1);

    // Title
    doc.fillColor(color).fontSize(14).text(title, { underline: true });

    doc.moveDown(0.5);

    // Items
    if (items && items.length) {
      items.forEach((item) => {
        doc
          .fillColor("#222428")
          .fontSize(11)
          .text("• " + item, {
            indent: 15,
          });
      });
    } else {
      doc.fillColor("#171a1e").text("N/A");
    }

    doc.moveDown(1.2);
  };

  // ================= SECTIONS =================
  section("Matching Skills", result.matchingSkills, "#22c55e");
  section("Missing Skills", result.missingSkills, "#ef4444");
  section("Strengths", result.strengths);
  section("Weaknesses", result.weaknesses, "#f59e0b");
  section("Improvements", result.improvements);
  section("ATS Tips", result.atsTips);
  section("Recommended Keywords", result.recommendedKeywords);
  section("Improved Resume Points", result.recommendedBulletPoints);

  // ================= FOOTER =================
  doc.moveDown(2);

  doc.fontSize(10).fillColor("#010102").text("Generated by InterviewPrep AI", {
    align: "center",
  });

  doc.end();
}

module.exports = generatePDF;
